### ISSUE TITLE
Remove whitespace after Banner Image 

### ISSUE THREAD

**Issue by vramana** [fcc-hyd/fcc-hyd.github.io#13]
![screenshot from 2016-09-05 18-53-45](https://cloud.githubusercontent.com/assets/3112509/18249178/479bfc5c-739a-11e6-920a-7c9df747f1e3.png)

**Comment by sudheerdarla** [comment]
I don't see any white space..after the banner image.

**Comment by vramana** [comment]
@sudheerdarla Look at where there image ends and scrollbar is present.

**Comment by sudheerdarla** [comment]
I am afraid that, from my side there is no white space.
By the way...What are these bugs you created or just normally raised bugs?

**Comment by vramana** [comment]
@sudheerdarla It only exists on large resolution screen (1920x1080). Zoom out then you will see it I think. 

We planned to make website for FreeCodeCamp Hyderabad for our community and help beginners with opensource as well. Currently the site is copy of templates with some minor modifications. The idea is to incrementally build the site modifying the template.

**Comment by sudheerdarla** [comment]
Well..nice then.

**Comment by himanshuchauhan** [comment]
Fixed the issue PR#14
