### ISSUE TITLE
Rebuild Website

### ISSUE THREAD

**Issue by vramana** [fcc-hyd/fcc-hyd.github.io#21]
Objectives: 
- [x] Make Better Banner
- [x] Fix header text color
- [x] Write Meetup formats
- [x] make it work with github pages
- [ ] Popup for each meetup format
- [x] Revamp Team
- [x] Add pofile pics for team 
- [ ] Revamp Contact Us 
- [x] Clean up CSS
- [x] Recreate gulpfile
- [x] Remove Unnecessary files
- [ ] Better background image
- [ ] Past Meetups & Future Meetups
- [ ] Decrease the size of mentor images

**Comment by udayk8139** [comment]
wowowowo :3
