### ISSUE TITLE
Next Meetup Timer

### ISSUE THREAD

**Issue by chakrihacker** [fcc-hyd/fcc-hyd.github.io#24]
Implement a timer using JS to countdown the time remaining for the next meetup

**Comment by IamAdiSri** [comment]
I'd like to work on this. Can this issue be assigned to me?

**Comment by IamAdiSri** [comment]
Also, what are the specifications for the time to next meetup? As in will only the date be given or will the time also be specified?

**Comment by chakrihacker** [comment]
display days:hours:minutes:seconds and the countdown should continue
