### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by a-kile** [fcc-hyd/fcc-hyd.github.io#26]
# Showcase

Our community has many good and talented people. It is always a good idea to showcase our talent.
I think there's a need for a showcase page, displaying really nice creations worth looking into.

**Comment by vramana** [comment]
@chakrihacker The issue needs more explict description.

@udayk8139 First step is to collect the work by our community members in a wiki. Once you have sufficient enough projects then we can think about the page.

**Comment by chakrihacker** [comment]
@vramana let uday start and we will start collecting projects in gitter

**Comment by vramana** [comment]
Okay
