### ISSUE TITLE
Feedback/ Activities Board

### ISSUE THREAD

**Issue by a-kile** [fcc-hyd/fcc-hyd.github.io#27]
# Thoughts

I think there should be a big jumbotron that will display live tweets, instagram images and fb posts .
This will show how active we are, and also encourage people to join us.

Especially if the tweets contain feedback on FCC HYD :dagger:

**Comment by realslimshanky** [comment]
I would like to work on this issue. Will send a PR soon.

**Comment by vramana** [comment]
@realslimshanky Please tell how you want to proceed first.

**Comment by realslimshanky** [comment]
@vramana a jumbotron can be added in place of fccBanner.png with a simple gradient or texture.
This jumbotron will take data from twitter, facebook and instagram APIs and will showcase the feeds like slides.

**Comment by vramana** [comment]
I don't know if we want to replace the banner. @chakrihacker thoughts?

**Comment by chakrihacker** [comment]
No need to replace FCC banner. It would be better if placed above contact us

**Comment by realslimshanky** [comment]
That'll look nice too. Like a stripe of updates which keeps flowing.

**Comment by a-kile** [comment]
Yeah :O

**Comment by a-kile** [comment]
@realslimshanky And also, you should use vh(viewport height) values instead of em, px, or % to specify the height of the jumbotron

**Comment by chakrihacker** [comment]
@a-kile it's not necessary to use vh

**Comment by a-kile** [comment]
@chakrihacker but it's great D:
