### ISSUE TITLE
Guide for adding member profile

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/fcc-hyd.github.io#36]
Need to create a guide to add members profiles, which members can follow to send their PR's and contribute to the project. Does anyone wanna work on this?

**Comment by srichakradhar** [comment]
let's add PNGs like, on the 2nd page of this: https://www.freecodecamp.com/challenges/get-set-for-our-api-development-projects ?

**Comment by srichakradhar** [comment]
[download](http://gifmaker.me/files/download/home/20161122/02/wPvQu8LF7i7B5tIJ7fULHb/output_nrk0ZB.gif) the GIF of how-to.

**Comment by sudheerdarla** [comment]
http://recordit.co/
try this chuck...it is perfect!!

**Comment by duttakapil** [comment]
Hey @srichakradhar, this Gif looks fine. Let's just start working on the guide. We can put it in the readme file and it will display on the main page here. Or we could create a new page on our website, inside the members folder, and host it on the website itself. We'll need good amount of content. I've create a new Google Doc for this and shared it with you guys. I'll try to contribute to it as soon as possible
