### ISSUE TITLE
[Suggestion] on moving site to free custom subdomain offered by https://js.org/

### ISSUE THREAD

**Issue by vinaypuppal** [fcc-hyd/fcc-hyd.github.io#40]
- https://js.org/ offers free custom sub domains for JavaScript focused projects which are hosted on GitHub Pages
- Instructions on how to do that can be found here https://github.com/js-org/dns.js.org
- wiki https://github.com/js-org/dns.js.org/wiki for more infomation

cc @vramana  and @duttakapil  what you guys think??

**Comment by duttakapil** [comment]
Let's do it @vinaypuppal. If I add you as a contributor, will you be able to take care of this?

**Comment by vramana** [comment]
I am not in favour of this. What is the purpose? We are not a **JavaScript focused project**. So by definition, I don't understand how they will approve the subdomain. 

Do we get more authenticity or something? A shorter url? Or are we doing it just because we can? I fail to see the rationale behind this.  @vinaypuppal Can you shed some light on this?

**Comment by keshavnarla** [comment]
I would prefer to have our own domain instead of being a sub-domain

**Comment by vinaypuppal** [comment]
@vramana 
> We are not a JavaScript focused project. So by definition, I don't understand how they will approve the subdomain.

As you can see in their [active CNAME list](https://github.com/js-org/dns.js.org/blob/master/cnames_active.js) they accepted few blogs and other kind of sites
- https://utscrooms.js.org/
- https://100dayz.js.org/
- http://youtube-box.js.org/

> What is the purpose?

-  A shorter url ? **Yes** https://fcc-hyd.js.org is better than long https://fcc-hyd.github.io
-  Are we doing it just because we can? **Yes** lets give it a try, if they accept its good otherwise we loose nothing right (except for 24hrs or till they/we make dns transition site will be down).
- Do we get more authenticity or something? **Yes** and **fcc-hyd** can become part of *js.org* community as well.

**Comment by duttakapil** [comment]
If we get a custom domain, can we set it up with [our GitHub site](http://fcc-hyd.github.io/)? I think it's possible, but I'm not sure how. And what domain name should we get?

**Comment by vinaypuppal** [comment]
@duttakapil 
> If we get a custom domain, can we set it up with our [GitHub site](http://fcc-hyd.github.io/)? I think it's possible, but I'm not sure how. 

yeah its possible, we need to add `CNAME` file to our repo with that custom domain and in domain DNS setting we should point `www/@` to `fcc-hyd.github.io` . 

And FYI [My Portfolio site](https://github.com/vinaypuppal/vinaypuppal.github.io) is hosted on GHPages only and in the repo you can see CNAME file.
