### ISSUE TITLE
Ideas for t-shirt design

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/fcc-hyd.github.io#44]
Post your ideas for t-shirt design's. The theme should be related to coding/development and our community activities.

**Comment by a-kile** [comment]
uh Maybe a hoodie with fcc-hyd logos and art 🗡

**Comment by Kamalnrf** [comment]
Black shirt with white logo

**Comment by duttakapil** [comment]
Something like this?
![black front](https://cloud.githubusercontent.com/assets/6577624/20930520/a4971e90-bbf3-11e6-9619-3fa80a73aa1b.png)
![black back](https://cloud.githubusercontent.com/assets/6577624/20930519/a4967bde-bbf3-11e6-8a29-893ec43922b9.png)

**Comment by srichakradhar** [comment]
![image](https://cloud.githubusercontent.com/assets/1732922/20976422/82f3ee14-bcc8-11e6-8a2f-a01d91115ded.png)

**Comment by srichakradhar** [comment]
![image](https://s-media-cache-ak0.pinimg.com/236x/3f/79/60/3f7960f9457a41ed58eec28d06a778f1.jpg)

**Comment by Kamalnrf** [comment]
We can also try other varients like green shirt with white logo ...

**Comment by duttakapil** [comment]
What do you guys think about the [black one with our logo](https://github.com/fcc-hyd/fcc-hyd.github.io/issues/44#issuecomment-265173619)?

**Comment by duttakapil** [comment]
@srichakradhar those are good, but don't think they are original. We should try to come up with some original line

**Comment by keshavnarla** [comment]
How about Black one with our logo in our original white+green colors

**Comment by srichakradhar** [comment]
![i wont fix ur computer](https://cloud.githubusercontent.com/assets/1732922/21194302/6f077d8e-c255-11e6-84b7-eff076506dfc.jpg)

**Comment by sudheerdarla** [comment]
![model1](https://cloud.githubusercontent.com/assets/16088040/21195259/12928540-c259-11e6-8e3d-6c9717ba23e9.png)

**Comment by srichakradhar** [comment]
Looks good @sudheerdarla . But, can we have the same font as our fcc logo?

**Comment by sudheerdarla** [comment]
Yes! Its just a font right? but, dont know that font will be available in **mydreamstore** editor!

**Comment by duttakapil** [comment]
I think we can share these in the chat and see how people respond. Based on that we can decide if we should print

**Comment by srichakradhar** [comment]
Coding should never feel lonely.
