### ISSUE TITLE
Create a web page for all our issues

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/fcc-hyd.github.io#45]
We need a page on our site that contains all our open GitHub issues, across all our projects. The purpose is to make it easier for our members to discover issues and contribute. It would be good if we can also filter the issues using labels, on the site.

**Comment by a-kile** [comment]
I feel like this is unnecessary, as github already has a nice and simple way to see all the issues. 👎

**Comment by duttakapil** [comment]
Your comment would have been helpful if you had explained how one can see all the issues from an organization across all their open source projects. I don't know of a way to do that

**Comment by a-kile** [comment]
I mean, why would a uhhhh i'd just not involve :P
