### ISSUE TITLE
background color of menu changes to odd colors

### ISSUE THREAD

**Issue by buoyantair** [fcc-hyd/fcc-hyd.github.io#51]
Someone must have altered the menu's code, the menu options are highlighted in wrong colors
Check this screeny out! 
![Image](http://image.prntscr.com/image/e1ae85d5377a480288ef73eb61a1ca67.png)

**Comment by duttakapil** [comment]
Can you make your title and comment more descriptive? Instead of linking to the image, you can insert it directly. That would help whoever chooses to contribute and fix this

**Comment by a-kile** [comment]
@duttakapil Okay... 👍

**Comment by Pk13055** [comment]
Can you add some relevant links/comments?

**Comment by boro741** [comment]
I'll work on this

**Comment by vinaypuppal** [comment]
@boro741 Actually we are redesigning this site, you can followup discussions at https://github.com/fcc-hyd/fcc-hyd/issues
